# Download Progvert.DBF
Start-BitsTransfer https://github.com/Delapro/DelaproInstallNet/raw/refs/heads/master/Doku/Client-Einrichtung-Dateien/PROGVERT.DBF

# NetzLW.BAT
Start-BitsTransfer https://raw.githubusercontent.com/Delapro/DelaproInstallNet/refs/heads/master/Doku/Client-Einrichtung-Dateien/NetzLWVerbinden.BAT

# TODO: DLPHD.ICO für Verknüpfung
# TODO: DLP_MAIN.INI
# TODO: DELAPRO.EXE
# TODO: Fernwartung-Verzeichnis mit AnyDesk und Teamviewer
